name: Scan PR for Banned Words in C++ Files

on:
  pull_request:

jobs:
  scan-for-banned-words:
    runs-on: ubuntu-latest
    steps:
    - name: Scan for banned words in PR diff (C++ files only)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Define the list of banned words
        banned_words=("foo" "bar")
        error=0

        # Get PR details
        PR_NUMBER=${{ github.event.pull_request.number }}
        OWNER=${{ github.repository.owner.login }}
        REPO=${{ github.event.repository.name }}

        # Fetch the PR diff from GitHub API
        curl -s -H "Accept: application/vnd.github.v3.diff" \
             -H "Authorization: token $GITHUB_TOKEN" \
             "https://api.github.com/repos/$OWNER/$REPO/pulls/$PR_NUMBER" > pr.diff

        # Initialize variables
        current_file=""
        process_file=0

        # Read the diff line by line
        while IFS= read -r line; do
          # Check for diff headers indicating a new file
          if [[ $line =~ ^diff\ --git\ a\/(.+)\ b\/(.+) ]]; then
            # Extract the file name
            current_file="${BASH_REMATCH[2]}"
            # Check if the file has a C++ extension
            if [[ $current_file =~ \.(cpp|cxx|cc|c|hpp|h|hxx|hh)$ ]]; then
              process_file=1
            else
              process_file=0
            fi
          elif [[ $process_file -eq 1 ]]; then
            # Check for added lines
            if [[ $line =~ ^\+[^+]{1} ]]; then
              added_line="${line:1}"  # Remove the '+' sign
              # Loop through each banned word
              for word in "${banned_words[@]}"; do
                if echo "$added_line" | grep -wq "$word"; then
                  echo "❌ Found banned word '$word' in file '$current_file':"
                  echo "$added_line"
                  error=1
                fi
              done
            fi
          fi
        done < pr.diff

        # Exit with error if any banned words were found
        if [[ $error -eq 1 ]]; then
          exit 1
        else
          echo "✅ No banned words found in added or changed lines of C++ files."
        fi
